-- ============================================================================
-- Migration 006: Phase 2 — Faculty Accomplishments, Research Upgrades, Leave Statuses
-- ============================================================================

-- 1. New table: faculty_accomplishments (using BIGINT to match faculty.id)
CREATE TABLE IF NOT EXISTS public.faculty_accomplishments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_id BIGINT REFERENCES public.faculty(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    accomplishment_type TEXT DEFAULT 'Seminar',
    description TEXT,
    date_achieved DATE,
    proof_file_name TEXT,
    proof_file_url TEXT,
    proof_file_path TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW())
);

-- 2. Alter faculty_research_projects: add authors (JSONB) and publication_url columns
ALTER TABLE public.faculty_research_projects
    ADD COLUMN IF NOT EXISTS authors JSONB DEFAULT '[]'::jsonb;

ALTER TABLE public.faculty_research_projects
    ADD COLUMN IF NOT EXISTS publication_url TEXT;

-- 3. Alter faculty_research_projects: expand status CHECK constraint
ALTER TABLE public.faculty_research_projects
    DROP CONSTRAINT IF EXISTS faculty_research_projects_status_check;

ALTER TABLE public.faculty_research_projects
    ADD CONSTRAINT faculty_research_projects_status_check
    CHECK (status IN (
        'Proposed', 'Ongoing',
        'Completed but not Published', 'Completed and Published',
        'Completed', 'Published', 'Patented'
    ));

-- 4. Alter faculty: expand status CHECK to include detailed leave types
ALTER TABLE public.faculty
    DROP CONSTRAINT IF EXISTS faculty_status_check;

ALTER TABLE public.faculty
    ADD CONSTRAINT faculty_status_check
    CHECK (status IN (
        'Active', 'Inactive', 'On Leave', 'Archived',
        'On Maternity Leave', 'On Study Leave',
        'On Sabbatical Leave', 'On Vacation/Sick Leave'
    ));

-- 5. Alter faculty: add leave tracking date columns
ALTER TABLE public.faculty
    ADD COLUMN IF NOT EXISTS leave_start_date DATE;

ALTER TABLE public.faculty
    ADD COLUMN IF NOT EXISTS leave_end_date DATE;

-- 6. New storage bucket for accomplishment proof files
INSERT INTO storage.buckets (id, name, public)
VALUES ('faculty-accomplishments', 'faculty-accomplishments', true)
ON CONFLICT (id) DO NOTHING;

-- 7. Storage policies for new bucket
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE policyname = 'Public read faculty-accomplishments'
          AND tablename = 'objects'
    ) THEN
        CREATE POLICY "Public read faculty-accomplishments" ON storage.objects
            FOR SELECT TO public
            USING (bucket_id = 'faculty-accomplishments');
    END IF;
END $$;

-- 8. RLS for faculty_accomplishments table
ALTER TABLE public.faculty_accomplishments ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE policyname = 'Authenticated full access to faculty_accomplishments'
          AND tablename = 'faculty_accomplishments'
    ) THEN
        CREATE POLICY "Authenticated full access to faculty_accomplishments"
            ON public.faculty_accomplishments
            FOR ALL TO authenticated
            USING (true) WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE policyname = 'Anon read access to faculty_accomplishments'
          AND tablename = 'faculty_accomplishments'
    ) THEN
        CREATE POLICY "Anon read access to faculty_accomplishments"
            ON public.faculty_accomplishments
            FOR SELECT TO anon
            USING (true);
    END IF;
END $$;
