-- ============================================================================
-- Migration 010: Accomplishment Report Workflow (5-Step Integration)
-- ============================================================================
-- Adds a dedicated table for tracking accomplishment report submissions
-- through the institutional sign-off chain:
--   Draft → Submitted → Chair Approved → Dean Approved
-- ============================================================================

-- 1. Create accomplishment_report_submissions table
CREATE TABLE IF NOT EXISTS public.accomplishment_report_submissions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_id      BIGINT REFERENCES public.faculty(id) ON DELETE CASCADE,
    report_type     TEXT NOT NULL DEFAULT 'offline'
                    CHECK (report_type IN ('offline', 'online')),
    period_start    DATE NOT NULL,
    period_end      DATE NOT NULL,
    
    -- Generated PDF storage
    report_pdf_url  TEXT,
    report_pdf_path TEXT,
    
    -- Approval status
    status          TEXT NOT NULL DEFAULT 'draft'
                    CHECK (status IN (
                        'draft',
                        'submitted',
                        'chair_approved',
                        'dean_approved',
                        'revision',
                        'rejected'
                    )),
    
    -- Chairperson review fields
    chair_reviewed_by       TEXT,
    chair_reviewed_by_id    BIGINT,
    chair_reviewed_at       TIMESTAMPTZ,
    chair_remarks           TEXT,
    
    -- Dean / Admin review fields
    dean_reviewed_by        TEXT,
    dean_reviewed_by_id     BIGINT,
    dean_reviewed_at        TIMESTAMPTZ,
    dean_remarks            TEXT,
    
    -- Snapshot of report configuration at time of submission
    -- Stores: { template, adminDesignation, workingHours, docsChecked, accomplishmentIds, ... }
    report_data     JSONB DEFAULT '{}'::jsonb,
    
    -- Resubmission tracking
    resubmission_count  INT DEFAULT 0,
    
    -- Timestamps
    submitted_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()),
    updated_at      TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW())
);

-- 2. RLS for accomplishment_report_submissions
ALTER TABLE public.accomplishment_report_submissions ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE policyname = 'Authenticated full access to accomplishment_report_submissions'
          AND tablename = 'accomplishment_report_submissions'
    ) THEN
        CREATE POLICY "Authenticated full access to accomplishment_report_submissions"
            ON public.accomplishment_report_submissions
            FOR ALL TO authenticated
            USING (true) WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE policyname = 'Anon read access to accomplishment_report_submissions'
          AND tablename = 'accomplishment_report_submissions'
    ) THEN
        CREATE POLICY "Anon read access to accomplishment_report_submissions"
            ON public.accomplishment_report_submissions
            FOR SELECT TO anon
            USING (true);
    END IF;
END $$;

-- 3. Index for faster faculty lookups
CREATE INDEX IF NOT EXISTS idx_ars_faculty_id
    ON public.accomplishment_report_submissions (faculty_id);

CREATE INDEX IF NOT EXISTS idx_ars_status
    ON public.accomplishment_report_submissions (status);

-- 4. Ensure faculty-accomplishments storage bucket accepts PDF uploads
-- (bucket already exists from migration 007, just ensure upload policy exists)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE policyname = 'Authenticated upload faculty-accomplishments'
          AND tablename = 'objects'
    ) THEN
        CREATE POLICY "Authenticated upload faculty-accomplishments" ON storage.objects
            FOR INSERT TO authenticated
            WITH CHECK (bucket_id = 'faculty-accomplishments');
    END IF;
END $$;
