-- ==============================================================================
-- CITE-Flow: Complete Document Vault & Storage Setup Script
-- Run this in your Supabase SQL Editor (Dashboard -> SQL Editor -> New Query)
-- ==============================================================================

-- 1. Create folders table if not exists
CREATE TABLE IF NOT EXISTS public.folders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    icon TEXT DEFAULT 'fa-folder',
    color TEXT DEFAULT '#6b21a8',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create documents table if not exists
CREATE TABLE IF NOT EXISTS public.documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    folder_id BIGINT REFERENCES public.folders(id) ON DELETE CASCADE,
    file_path TEXT NOT NULL,
    mime_type TEXT,
    size_bytes BIGINT,
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    uploaded_by TEXT
);

-- 3. Enable RLS on database tables
ALTER TABLE public.folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;

-- 4. Set RLS Policies for folders (anon and authenticated)
DROP POLICY IF EXISTS "Allow all for folders" ON public.folders;
DROP POLICY IF EXISTS "Allow all for authenticated users - folders" ON public.folders;
CREATE POLICY "Allow all for folders" ON public.folders
    FOR ALL TO public, anon, authenticated
    USING (true)
    WITH CHECK (true);

-- 5. Set RLS Policies for documents (anon and authenticated)
DROP POLICY IF EXISTS "Allow all for documents" ON public.documents;
DROP POLICY IF EXISTS "Allow all for authenticated users - documents" ON public.documents;
CREATE POLICY "Allow all for documents" ON public.documents
    FOR ALL TO public, anon, authenticated
    USING (true)
    WITH CHECK (true);

-- 6. Create indexes for high performance
CREATE INDEX IF NOT EXISTS idx_documents_folder_id ON public.documents(folder_id);
CREATE INDEX IF NOT EXISTS idx_documents_uploaded_at ON public.documents(uploaded_at DESC);
CREATE INDEX IF NOT EXISTS idx_folders_name ON public.folders(name);

-- 7. Initialize Storage Bucket 'documents' as PRIVATE
UPDATE storage.buckets SET public = false WHERE id = 'documents';
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('documents', 'documents', false, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET 
    name = 'documents',
    public = false;

-- 8. Storage Object Policies for 'documents' bucket
-- Exclusively restricted to bucket_id = 'documents' and TO authenticated (Admins)
-- Does NOT touch any other bucket (e.g. wf-submissions, faculty-accomplishments, etc.)

-- Step A: Drop old storage policies FIRST so they don't block dropping old functions
DROP POLICY IF EXISTS "documents_storage_select_admin" ON storage.objects;
DROP POLICY IF EXISTS "documents_storage_insert_admin" ON storage.objects;
DROP POLICY IF EXISTS "documents_storage_update_admin" ON storage.objects;
DROP POLICY IF EXISTS "documents_storage_delete_admin" ON storage.objects;
DROP POLICY IF EXISTS "documents_bucket_insert_document_vault" ON storage.objects;
DROP POLICY IF EXISTS "Public can view documents storage" ON storage.objects;
DROP POLICY IF EXISTS "Public can insert documents storage" ON storage.objects;
DROP POLICY IF EXISTS "Public can update documents storage" ON storage.objects;
DROP POLICY IF EXISTS "Public can delete documents storage" ON storage.objects;
DROP POLICY IF EXISTS "Allow public delete documents bucket" ON storage.objects;
DROP POLICY IF EXISTS "Allow public read documents bucket" ON storage.objects;
DROP POLICY IF EXISTS "Allow public update documents bucket" ON storage.objects;
DROP POLICY IF EXISTS "Allow public upload documents bucket" ON storage.objects;

-- Step B: Drop both function overloads to fix "ERROR: 42725: function is_document_vault_admin() is not unique"
DROP FUNCTION IF EXISTS public.is_document_vault_admin() CASCADE;
DROP FUNCTION IF EXISTS public.is_document_vault_admin(uuid) CASCADE;

-- Step C: Create a single unambiguous 0-argument helper function
CREATE OR REPLACE FUNCTION public.is_document_vault_admin()
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    target_uid uuid;
    target_email text;
BEGIN
    target_uid := auth.uid();
    IF target_uid IS NULL THEN
        RETURN false;
    END IF;

    -- Look up email from auth.users (SECURITY DEFINER allows reading auth.users)
    SELECT lower(trim(email)) INTO target_email
    FROM auth.users
    WHERE id = target_uid;

    -- 1. Checked against admin_profiles table (by id or email)
    IF EXISTS (
        SELECT 1
        FROM public.admin_profiles ap
        WHERE (ap.id::text = target_uid::text
           OR (target_email IS NOT NULL AND lower(trim(coalesce(ap.email, ''))) = target_email))
          AND lower(coalesce(ap.role, 'administrator')) NOT LIKE '%chair%'
    ) THEN
        RETURN true;
    END IF;

    -- 2. Checked against faculty table with admin role, position, or admin_access flag
    IF EXISTS (
        SELECT 1
        FROM public.faculty f
        WHERE (f.auth_user_id::text = target_uid::text
           OR (target_email IS NOT NULL AND lower(trim(coalesce(f.email, f.existing_email, ''))) = target_email))
          AND (
            lower(coalesce(f.role, f.position, '')) LIKE '%admin%'
            OR lower(coalesce(f.role, f.position, '')) IN ('dean', 'secretary', 'college secretary', 'college_secretary', 'superadmin', 'director')
            OR coalesce(f.admin_access, false) = true
          )
          AND (
            lower(coalesce(f.role, f.position, '')) NOT LIKE '%chair%'
            OR coalesce(f.admin_access, false) = true
          )
    ) THEN
        RETURN true;
    END IF;

    -- 3. Checked against auth.users metadata (raw_user_meta_data & raw_app_meta_data)
    IF EXISTS (
        SELECT 1
        FROM auth.users u
        WHERE u.id = target_uid
          AND (
            lower(coalesce(u.raw_user_meta_data ->> 'role', '')) LIKE '%admin%'
            OR lower(coalesce(u.raw_user_meta_data ->> 'role', '')) IN ('dean', 'secretary', 'college secretary', 'superadmin', 'director')
            OR lower(coalesce(u.raw_app_meta_data ->> 'role', '')) LIKE '%admin%'
            OR lower(coalesce(u.raw_app_meta_data ->> 'role', '')) IN ('dean', 'secretary', 'college secretary', 'superadmin', 'director')
          )
          AND position('chair' in lower(coalesce(u.raw_user_meta_data ->> 'role', ''))) = 0
    ) THEN
        RETURN true;
    END IF;

    -- 4. Shared CITE-Flow wf_is_final_approver() if defined and caller is the session user
    IF to_regprocedure('public.wf_is_final_approver()') IS NOT NULL THEN
        IF public.wf_is_final_approver() THEN
            RETURN true;
        END IF;
    END IF;

    RETURN false;
END;
$$;

GRANT EXECUTE ON FUNCTION public.is_document_vault_admin() TO authenticated, anon;

-- Step D: Ensure authenticated users can query bucket metadata for 'documents'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE schemaname = 'storage' AND tablename = 'buckets' AND policyname = 'authenticated_read_documents_bucket'
    ) THEN
        CREATE POLICY "authenticated_read_documents_bucket" ON storage.buckets
            FOR SELECT TO authenticated
            USING (id = 'documents' OR public = true);
    END IF;
END $$;

-- Step E: Clean and strictly scoped policies for 'documents' bucket only

-- Policy 1: List and view/download documents from 'documents' bucket
CREATE POLICY "documents_storage_select_admin" ON storage.objects
    FOR SELECT TO authenticated
    USING (
        bucket_id = 'documents'
        AND public.is_document_vault_admin()
    );

-- Policy 2: Upload new files to 'documents' bucket
CREATE POLICY "documents_storage_insert_admin" ON storage.objects
    FOR INSERT TO authenticated
    WITH CHECK (
        bucket_id = 'documents'
        AND public.is_document_vault_admin()
    );

-- Policy 3: Update existing files in 'documents' bucket (required for upsert: true)
CREATE POLICY "documents_storage_update_admin" ON storage.objects
    FOR UPDATE TO authenticated
    USING (
        bucket_id = 'documents'
        AND public.is_document_vault_admin()
    )
    WITH CHECK (
        bucket_id = 'documents'
        AND public.is_document_vault_admin()
    );

-- Policy 4: Delete files from 'documents' bucket
CREATE POLICY "documents_storage_delete_admin" ON storage.objects
    FOR DELETE TO authenticated
    USING (
        bucket_id = 'documents'
        AND public.is_document_vault_admin()
    );

-- 9. Refresh Schema Cache
NOTIFY pgrst, 'reload schema';